apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-demo-app
  labels:
    app: demo-app
spec:
  selector:
    matchLabels:
      app: demo-app
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/webapp/config"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/webapp/config" -}}
          
             export USERNAME="{{ .Data.data.username }}"
             export PASSWORD="{{ .Data.data.password }}"
          
          {{- end }}
        vault.hashicorp.com/role: "webapp"
      labels:
        app: demo-app
    spec:
      serviceAccountName: vault
      containers:
      - name: demo-app
        image: nadamekki/vault-demo-app:v2.0.2
        command:
          ['/bin/bash','-c']
        args:
          ['source /vault/secrets/config && npm run start']
        
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  labels:
    app: vault
